theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
title: Deep Declarative Networks CVPR 2020 Workshop
#description: 
#logo: [Location of the logo]
#show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
